export const ADD_POTION = 'ADD_POTION';
export const DELETE_POTION = 'DELETE_POTION';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETING_POTION = 'DELETING_POTION';
export const EDITING_POTION = 'EDITING_POTION';
export const SELECT_POTION = 'SELECT_POTION';